image: php:8.3-fpm-bullseye # Utilisation de Bullseye (Debian 11) pour coller à ton OS

stages:
  - build
  - test
  - docker_check

# Cache pour accélérer les installations de Composer
cache:
  paths:
    - vendor/

variables:
  MYSQL_DATABASE: testing
  MYSQL_ROOT_PASSWORD: root
  DB_HOST: mysql

before_script:
  - apt-get update -yqq
  - apt-get install -yqq libpq-dev libzip-dev zip unzip git mariadb-client
  - docker-php-ext-install pdo_mysql zip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

install_dependencies:
  stage: build
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
  artifacts:
    paths:
      - vendor/
    expire_in: 1 hour

run_tests:
  stage: test
  services:
    - mysql:8.0
  dependencies:
    - install_dependencies
  script:
    - cp .env.example .env.testing
    - php artisan key:generate --env=testing
    - php artisan migrate --env=testing --force
    - php artisan test

check_docker_build:
  stage: docker_check
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t laravelfirst:test .