image: php:8.3-fpm

services:
  - name: mysql:8.0
    alias: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

stages:
  - test

variables:
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: 3306
  DB_DATABASE: laravel_db
  DB_USERNAME: root
  DB_PASSWORD: secret

before_script:
  - apt-get update && apt-get install -y unzip git curl libpng-dev libonig-dev libxml2-dev zip mariadb-client
  - docker-php-ext-install pdo_mysql
  - curl -sS https://getcomposer.org/installer | php
  - mv composer.phar /usr/local/bin/composer
  - composer install --no-interaction --prefer-dist
  - mysql -h "$DB_HOST" -u "$DB_USERNAME" -p"$DB_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS \`$DB_DATABASE\`;"

test:
  stage: test
  script:
    - php artisan migrate --force
    - php artisan test
  only:
    - ajout_ci_cd